name: simple-swap
services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        build:
            context: ..
            dockerfile: .local/Dockerfile
        restart: always
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ..:/app
        command:
            [
                "sh",
                "-c",
                "python infrastructure/psql/init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload",
            ]

volumes:
    pgdata:
